version: '3'
services:
  sql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 436501
      MYSQL_DATABASE: intellicite
      MYSQL_USER: admin
      MYSQL_PASSWORD: 436501