version: '3'
services:
  express-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar

volumes:
  mongo-db: