version: '3'
services:
  express-app:
    build: ./
    image: mastermobo/intellicite:web-api-latest
    environment:
      - PORT=3000
    depends_on:
      - database
  
  database:
    image: mongo
    volumes:
      - mongo-db:/data/db

  load-balancer:
    image: nginx:stable-alpine
      
volumes:
  mongo-db: