version: '3'
services:
  express-app:
    depends_on:
      - database
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src:ro
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev

  load-balancer:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf:ro

  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar