version: '3'
services:
  express-app:
    depends_on:
      - database
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}

      - PORT=${PORT}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_IP=${MONGO_IP}

      - SEARCH_SERVICE_IP=${SEARCH_SERVICE_IP}
    
  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  load-balancer:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/etc/certs/fullchain.crt:/etc/nginx/ssl/fullchain.crt:ro
      - /root/etc/certs/intellicite.online.key:/etc/nginx/certs/intellicite.online.key:ro