version: '3'
services:
  express-app:
    build: ./web-api
    environment:
      - PORT=3000
    depends_on:
      - database

  database:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar

volumes:
  mongo-db: