FROM python:3.9

WORKDIR /app

COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader stopwords

RUN python -m nltk.downloader wordnet

COPY . .

CMD [ "python", "main.py" ]
