version: '3'
services:
  search-api:
    image: mastermobo/intellicite:search-api-latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - KAGGLE_USERNAME=buidangkhoa
      - KAGGLE_KEY=495bdf9d087690b2212b0edfc6c10acc
    depends_on:
      - es01
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=my-docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -k http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  es_data:
    driver: local