version: '3'
# The lables are what GPT gave me to do the following need:
# GPT: adjust the URI prefixes (/text_processing, /search, /ranking, /sentiment_analysis) to fit your application's routing needs.
services:
  text_processing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.text_processing.rule=PathPrefix(`/text_processing`)"

  search:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.search.rule=PathPrefix(`/search`)"
      - "traefik.http.services.search.loadbalancer.server.port=5000"
    depends_on:
      - text_processing

  ranking:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.ranking.rule=PathPrefix(`/ranking`)"
      - "traefik.http.services.ranking.loadbalancer.server.port=5000"
    depends_on:
      - search

  sentiment_analysis:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.sentiment_analysis.rule=PathPrefix(`/sentiment_analysis`)"
      - "traefik.http.services.sentiment_analysis.loadbalancer.server.port=5000"
    depends_on:
      - ranking
